import DBManager from './storageManager.mjs';

class User {
    constructor(email, pswHash, name, id = null) {
      this.email = email;
      this.pswHash = pswHash;
      this.name = name;
      this.id = id;
    }
  
    async save() {
      try {
        if (this.id == null) {
          // Create new user
          const newUser = await DBManager.createUser(this);
          this.id = newUser.id; // Update user's id with the one generated by the database
        } else {
          // Update existing user
          await DBManager.updateUser(this);
        }
      } catch (error) {
        // Handle error if DBManager fails
        console.error('Error saving user:', error);
        throw new Error('Failed to save user');
      }
    }
  
    async delete() {
      try {
        await DBManager.deleteUser(this);
      } catch (error) {
        // Handle error if DBManager fails
        console.error('Error deleting user:', error);
        throw new Error('Failed to delete user');
      }
    }
  }
  
  export default User;